In [2]:
import numpy as np
from scipy.optimize import minimize



In [54]:
nt = 101
time = np.linspace(0,1,nt)
display(time.shape)


(101,)

In [51]:
## initial conditions

q0 = np.array([[1, 0, 0,0], 
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]])
display(x0)
u0 = np.array([[1.0], [0.5], [0.5]])
display(u0)
u_initials = u0*np.ones((3,101))
display(u_initials.shape)

## our initial conditions through the time line are the same. 
q0_flatten = q0.flatten()
q0_flatten = np.reshape(q0_flatten, (16, 1))
display(q0_flatten)
q_initials = q0_flatten*np.ones((1, 101))
display(q_initials.shape)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

array([[1. ],
       [0.5],
       [0.5]])

(3, 101)

array([[1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1]])

(16, 101)

In [53]:
## stack q and u initials for 101 time step into one matrix
state_initials = np.vstack((q_initials, u_initials))
display(state_initials.shape)

(19, 101)

In [63]:
from scipy.integrate import quad

def integrand(state):
    c1, c2,c3 = 0.5
    u1 = state[17, :]
    u2 = state[18, :]
    u3 = state[19, :]
    return c1*u1**2 + c2*u2**2 + c3*u3**2

## develop objective function
def objective(state):
    c1, c2,c3 = 0.5
    u1 = state[17, :]
    u2 = state[18, :]
    u3 = state[19, :]
    min_target = quad(integrand, 0, 1)
    
    
    return min_tatger



In [ ]:
def constraint1(state):
    return x[0]*x[1]*x[2]*x[3]-25.0

def constraint2(state_initials):
    return state_initials

def constraint3(state_initials):
    return state_initials